---
title: "FREE FARMS"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    logo: images/logo.JPG
    favicon: images/logo.JPG
runtime: shiny_prerendered

---

```{r, context = "setup"}
options(shiny.port=9999)
library(flexdashboard)
library(plyr)
library(dplyr)
library(DT)
library(stringr)
library(tidyr)
library(highcharter)
library(rmarkdown)
library(xts)
library(dbplyr)
#library(future)
#library(foreach)
library(shinyjs)
library(purrr)
library(readr)
library(kableExtra)
library(rhandsontable)
library(DBI)

#source("funciones.R")







```

```{r context = "server-start"}
library(forecast)


#carga de las bases de datos
source("dbenv.R")

source("freefarmsFun.R")
   
   
#reactivos base de datos
dbr <- reactiveValues(

productores = dbenv$productores%>%
  collect(),

telefonos = dbenv$telefonos%>%
  collect(),

pallets = dbenv$pallets%>%
  collect(),

pallets_reg = dbenv$pallets_reg%>%
  collect())


```


```{r context = "server"}
resumen_prod <- reactive({
  
  
  
  dbr$productores%>%
  mutate(Nombre_completo = paste(Nombre, Apellido_paterno, Apellido_materno))%>%
  select(Id_productor, Clave_productor, Nombre_completo)})


dataRP <- reactive({
    resumen_prod()%>%
    mutate(
      Acciones = shinyInput(actionButton, 
                          resumen_prod()$Clave_productor, 
                          'editProd_', 
                          label = "Editar", 
                          onclick = 'Shiny.onInputChange(\"editProd\",  this.id)'))
     # stringsAsFactors = FALSE,
      #row.names = 1:length(resumen_prod()$Id_productor))
  }) 


output$Resumen_prod <- renderDT(
  dataRP()%>%
    arrange(Clave_productor), escape = FALSE, selection = 'none')





```
Productores
========================================================
###Productores
```{r}

actionButton("Alta_productor", "Agregar Productor")
DTOutput("Resumen_prod")
```


```{r context = "server"}

Clave <- reactive({as.numeric(strsplit(input$editProd, "_")[[1]][2])})
  
  Name <- reactive({
    
    
    
    resumen_prod()%>%
      filter(Clave_productor == Clave())%>%
      mutate(Clave_nombre = paste(Clave_productor, Nombre_completo))%>%
      select(Clave_nombre)}) 
  
  datos <- reactive({
    dbr$productores%>%
       select(-Usuario_creacion, 
             -Fecha_creacion,  
             -Cancelado, -Usuario_cancel, -Fecha_cancel, -Motivo_cancel)%>%
    filter(Clave_productor == Clave())%>%
    gather("Campo", "Valor")}) 
  
  contactos <- reactive({
    dbr$telefonos%>%
    filter(Clave_productor == Clave())%>%
    select(Contacto)
  })
  
  
    observeEvent(input$Editar_datos,{
    
    showModal(
       modalDialog(title = Name(),
      tabsetPanel(
          tabPanel("Contactos", HTML(kable3(contactos()))),
          tabPanel("Datos",  rHandsontableOutput("Prod_edit"))
        ),
      footer = tagList(
          actionButton("Guardar_datos", "Guardar", 
                       icon = icon("window-close", 
                                class = NULL, 
                                lib = "font-awesome")),
          modalButton("Cancelar", 
                    icon = icon("window-close", 
                                class = NULL, 
                                lib = "font-awesome")))
      
    
 
        ))
  
  })
    
#Datos editados
  
  output$Prod_edit <- renderRHandsontable(rhandsontable(datos())%>%
                     hot_col("Campo", readOnly = TRUE))
  
  trigger_datos <- reactive({
    if(is.null(input$Datos)){return(datos())}
    else if(!identical(datos(),input$Datos)){
      # hot.to.df function will convert your updated table into the dataframe
      as.data.frame(hot_to_r(input$Datos))
    }
  })
  
  observeEvent(input$Guardar_datos,{
    
      input$Prod_edit%>%
        hot_to_r()%>%
      spread("Campo", "Valor")%>%
    dbUpdateRow("Clave_productor", "productores", 
                    Clave(), 
                    conn = con)
      
    
      removeModal()
  })




 observeEvent(input$editProd,{
   showModal(
      
    modalDialog(title = Name(),
      tabsetPanel(
          tabPanel("Contactos",  HTML(kable3(contactos()))),
          tabPanel("Datos",  HTML(kable3(datos())))
        ),
      footer = tagList(
          actionButton("Editar_datos", "Editar"),
          modalButton("CERRAR", 
                    icon = icon("window-close", 
                                class = NULL, 
                                lib = "font-awesome"))
        )))
   
   
   dbr$productores <-  dbenv$productores%>%
  collect()

 dbr$telefonos <-  dbenv$telefonos%>%
  collect()
   
   
   
   
   
 })
```

```{r context = "server"}
#Modal Agregar Productor

#Formulario Alta

output$Test_clave_productor <- renderUI({
  if(input$Nueva_clave %in% dbr$productores$Clave_productor){
 paste("Esta Clave ya esta siendo usada")
}
  })

#Alta productores  
observeEvent(input$Alta_productor,
             {
               showModal(
                 modalDialog(
                  title = "Escriba los datos del productor",
                  tabsetPanel(
                    tabPanel(labelMandatory("Nombre"),
                             numericInput("Nueva_clave", label = "Clave Productor", value = max(c(max(dbr$productores$Clave_productor),999)) + 1),
                             textInput("Nombre_productor", label = labelMandatory("Nombre") ),
                             textInput("Apellido_paterno", label = labelMandatory("Apellido Paterno")),
                             textInput("Apellido_materno", label = labelMandatory("Apellido Materno")),
                             uiOutput("Test_clave_productor"),
                             shinyjs::useShinyjs(),
                             shinyjs::inlineCSS(appCSS)
                    #actionButton("Agregar_huerta","Agregar Huerta")
                ),
                tabPanel("Datos", uiOutput("Direccion_alta")),
                tabPanel("Contactos", uiOutput("Contactos_alta")),
                tabPanel("Facturacion", uiOutput("Facturacion_alta")),
                tabPanel("Bancarios", uiOutput("Bancarios_alta")),
                tabPanel(labelMandatory("Huerta"), uiOutput("Huertas_alta"))),
                 # tags$head(tags$style(".modal-body{ min-height:700px}")),
                  size = "l",
                  footer =  tagList(
                    div(
                      style="display: inline-block;vertical-align:top; width: 150px;",
                      uiOutput("Guardar_alta")),
                    div(
                      style="display: inline-block;vertical-align:top; width: 150px;",
                      actionButton("Cerrar_alta", "CERRAR", 
                                # onclick = Shiny.onInputChange("output.Datos_alta", prueba),
                                 icon = icon("window-close", 
                                            class = NULL, 
                                            lib = "font-awesome"))))
                 )
               )
               
             }
             )

productor_alta <- reactive({
  data.frame(
    Clave_productor = input$Nueva_clave,
    Nombre = input$Nombre_productor,
    Apellido_paterno = input$Apellido_paterno,
    Apellido_materno = input$Apellido_materno,
    Direccion = ifelse(is.null(input$Direccion_productorAlta), "", input$Direccion_productorAlta),
    Localidad = ifelse(is.null(input$Localidad_productorAlta), "", input$Localidad_productorAlta),
    Municipio = ifelse(is.null(input$Municipio_productorAlta), "", input$Municipio_productorAlta),
    Estado = ifelse(is.null(input$Estado_productorAlta), "", input$Estado_productorAlta),
    RFC = ifelse(is.null(input$Rfc), "", input$Rfc),
    Nombre_facturacion = ifelse(is.null(input$Nombre_facturacion), "", input$Nombre_facturacion),
    Nombre_contador = ifelse(is.null(input$Nombre_contador), "", input$Nombre_contador),
    Correo_contador = ifelse(is.null(input$Correo_contador), "", input$Correo_contador),
    Telefono_contador = ifelse(is.null(input$Telefono_contador), "", input$Telefono_contador)
    
  )
}) 

#Formularios Alta

output$Direccion_alta <- renderUI({
  tagList(
  div(textInput("Direccion_productorAlta", "Direccion", value = "")),
  div(textInput("Localidad_productorAlta", "Localidad", value = "")),
  div(textInput("Municipio_productorAlta", "Municipio", value =  "TANGANCICUARO")),  
  div(textInput("Estado_productorAlta", "Estado", value  = "MICHOACAN"))
  )
  })
  
observeEvent(input$Telefono_alta, {
  cat(input$Direccion_productorAlta)
})

output$Contactos_alta <- renderUI ({
  tagList(
  div(textInput("Telefono_alta", "Telefono", value = "")),
  div(textInput("Celular_alta", "Celular", value = "")),
  div(textInput("Correo_alta", "E-mail", value = "")))
  
})

contactos_alta <- reactive({
  data.frame(Telefono_alta = ifelse(is.null(input$Telefono_alta),"", input$Telefono_alta),
             Celular_alta = ifelse(is.null(input$Celular_alta), "", input$Celular_alta),
             Correo_alta = ifelse(is.null(input$Correo_alta), "", input$Correo_alta)
  )%>%
    gather("Tipo","Contacto")%>%
    filter(Contacto != "")%>%
    mutate(Tipo = ifelse(Tipo == "Telefono_alta", "Casa",
                         ifelse(Tipo == "Celular_alta", "Celular",
                                ifelse(Tipo == "Correo_alta", "E-mail", ""))),
           Clave_productor = input$Nueva_clave)
})




output$Facturacion_alta <- renderUI({
  tagList(
    div(textInput("Nombre_facturacion", "Nombre o Razon Social", value = "")),
    div(textInput("Rfc", "RFC", value = "")),
    div(textInput("Nombre_contador", "Nombre del Contador", value = "")),
    div(textInput("Correo_contador", "E-mail del Contador", value = "")),
    div(textInput("Telefono_contador", "Telefono del contador", value = ""))
    
    
  )
})

output$Bancarios_alta <- renderUI({
  tagList(
    div(textInput("Titular", "Titular de la cuenta", value = "")),
    div(textInput("Banco", "Banco", value = "")),
    div(textInput("Cuenta", "Cuenta", value = "")),
    div(textInput("CLABE", "CLABE", value = ""))
    
  )
})


#Formulario huertas



output$Huertas_alta <- renderUI({
  tagList(
    div(textInput("Nombre_huerta", labelMandatory("Nombre de la Huerta")), style="display: inline-block;vertical-align:top; width: 300px;"),
    div(textInput("Alias_huerta", "Alias"), style="display: inline-block;vertical-align:top; width: 300px;"),
    tags$br(),
    div(numericInput("Superficie_huerta", labelMandatory("Superficie de la Huerta"), value = 0), style="display: inline-block;vertical-align:top; width: 300px;"),
    div(numericInput(inputId = "No_sectores",
                                       label = labelMandatory("Numero de Sectores"), 
                                       value = 1, min = 1
                                        ),style="display: inline-block;vertical-align:top; width: 300px;"),
    tags$br(),
    div(selectizeInput("Fruta_huerta", 
                       label = labelMandatory("Fruta"), 
                       choices = c("ZARZAMORA"), 
                       options = list(placeholder = "ZARZAMORA")), style="display: inline-block;vertical-align:top; width: 300px;"),
    div(textInput("Direccion_huerta", labelMandatory("Ubicacion")), style="display: inline-block;vertical-align:top; width: 300px;"),
    tags$br(),
    div(textInput("Localidad_huerta", labelMandatory("Localidad")), style="display: inline-block;vertical-align:top; width: 300px;"),
    div(textInput("Municipio_huerta", "Municipio", value = "TANGANCICUARO"), style="display: inline-block;vertical-align:top; width: 300px;"),
    div(textInput("Estado_huerta", "Estado", value = "MICHOACAN"), style="display: inline-block;vertical-align:top; width: 300px;"),
    tags$br(),
    div(rHandsontableOutput("Sectores_alta"))
  )
  
})



labelMandatory <- function(label) {
  tagList(
    label,
    span("*", class = "mandatory_star")
  )
}
  #Formulario Sectores

output$Sectores_alta <- renderRHandsontable(
  rhandsontable(
    data.frame(
      Clave_sector = 1:input$No_sectores,
      Superficie = input$Superficie_huerta/input$No_sectores
    )%>%
      mutate(Nombre = paste("SECTOR ", Clave_sector))
  )
)



#mandatorios Alta Productor
mandatoryAlta <- c("Nueva_clave", "Nombre_productor", "Apellido_paterno", "Apellido_materno")


 mandatoryFilled <- reactive({
  # check if all mandatory fields have a value
  mandatoryFilled <-
    vapply(mandatoryAlta,
           function(x) {
             !is.null(input[[x]]) && input[[x]] != ""
           },
           logical(1))
 
   all(mandatoryFilled)
  
  
  
})
 
 
 
 
output$Guardar_alta <- renderUI({
  if(mandatoryFilled()){
    actionButton(inputId = "Guardar_alta", "Guardar")
    }else(paste("Favor de llenar los campos con *"))
}) 
 

#Cerrar Alta
observeEvent(input$Cerrar_alta,{
 # output$Datos_alta
  removeModal()})

#Guardar Alta


cuentas_alta <- reactive({
  data.frame(
    Beneficiario = input$Titular,
    Banco = input$Banco,
    Cuenta = input$Cuenta,
    Clabe = input$CLABE 
  )%>%
    mutate(Clave_productor = input$Nueva_clave)
  
})



huertas_alta <- reactive({
  data.frame(
    Clave_huerta = 1,
    Clave_productor = input$Nueva_clave,
    Nombre = input$Nombre_huerta,
    Alias = input$Alias_huerta,
    Superficie = input$Superficie_huerta,
    Direccion = input$Direccion_huerta,
    Clave_fruta = 1,
    Localidad = input$Localidad_huerta,
    Municipio = input$Municipio_huerta,
    Estado = input$Estado_huerta,
    Zona = "",
    Activo = "A"
  )
})  


sectores_alta = reactive({
  input$Sectores_alta%>%
    hot_to_r()%>%
    mutate(Clave_productor = input$Nueva_clave,
           Clave_huerta = 1)
})

observeEvent(input$Guardar_alta,
             {
               tryCatch({
              dbWithTransaction(con,{
                   
              dbWriteTable(value = productor_alta(), name = "productores", conn = con, append = TRUE)
                 
              dbWriteTable(value =  contactos_alta(), name = "productoresContactos", conn = con , append = TRUE)
              
              dbWriteTable(value = cuentas_alta(),
                              name = "productoresCuentas", conn = con, append = TRUE)
              
              dbWriteTable(value = huertas_alta(), name = "huertas", conn = con, append = TRUE)
              
              dbWriteTable(value = sectores_alta(), name = "sectores",conn = con, append = TRUE)
              })
                 },error = function(err){
                   print(paste("My errr", err))
                   #dbRollback(con)
                 },warning = function(w){
                     print(paste("My war:", w))
                   },
            finally = {
              
              #dbCommit(con)
              
              removeModal()
            })
             })



observeEvent(input$Agregar_huerta,
             {
               showModal(
                 modalDialog(
                   title = "HUERTA",
               tabsetPanel(
                 tabPanel("Huerta",
                          rHandsontableOutput("Huertas_alta")),
                 tabPanel("Sectores",
                          numericInput(inputId = "No_sectores",
                                       label = "Numero de Sectores", 
                                       value = 1
                                        ),
                          rHandsontableOutput("Sectores_alta")
                          )
               )
                 )
               )
             })




```

PRECIOS
==================================================================================

inputs {.sidebar}
----------------------------------------------------------------------------


```{r}
options(shiny.port=9999)

selectInput("Fruta_p", "Frutas", choices = c("Zarzamora", "Arandano"), selected = "Zarzamora")


actionButton("Update", "Actualizar usda" )

selectInput("Cat_usda", "Categoria Usda", choices = c("Precio", "Volumen"))

selectInput("Tipo_p", "Tipo de grafico", choices = c("Descomposicion", "Seasonal", "Proyeccion"),
            selected = "Proyeccion")

```


```{r, context = "server"}
fondoplot <- "transparent"
areacolor <- "rgba(6,144,207,.8)"

zar_usda <-  reactive({
  if(input$Cat_usda == "Precio"){
  zar.usda()}else{
    readRDS(paste0("mov", "Blackberries", ".RDS")) 
}})

ara_usda <- reactive({
  if(input$Cat_usda == "Precio"){
  ara.usda()}else{
    readRDS(paste0("mov", "Blueberries", ".RDS"))  
  }
})

observeEvent(input$Update, getUsda())

```




```{r, context = "server"}
output$Precios_master <- renderHighchart( 
  
      if(input$Tipo_p == "Descomposicion"){
        if(input$Fruta_p == "Zarzamora"){ 
        fruta  <- zar_usda()$Close%>%
            apply.weekly(mean)
       }else{
         if(input$Fruta_p == "Arandano"){
        fruta <- ara_usda()$Close%>%
          apply.weekly(mean)
         }
      }
    attr(fruta, 'frequency') <- 52.25
    
    fruta_dec <- decompose.xts(fruta$Close)
    
  highchart(type = "stock",
            list(rangeSelector = list(
                                    selected = 4)))%>%
  hc_chart(backgroundColor = fondoplot)%>%
  hc_yAxis_multiples(
    create_yaxis(4, 
                 height = c(1, 1, 1,1), 
                 turnopposite = TRUE))%>%
  hc_add_series(fruta_dec$x, yAxis = 0, name = "Observado")%>%
  hc_add_series(fruta_dec$seasonal, yAxis = 1, name = "Seasonal", color = "rgba(236, 85, 226, .91)")%>%
  hc_add_series(fruta_dec$trend, yAxis = 2, name = "Tendencia")%>%
  hc_add_series(fruta_dec$random, yAxis = 3, name = "Aleatorio")%>%
  hc_tooltip(crosshair = TRUE,
             shared = TRUE,
             split = FALSE)%>%
  hc_xAxis(type = 'datetime',
           dateTimeLabelFormats = list(day = '%e of %b'))
    }else{
      
      if(input$Tipo_p == "Seasonal"){
      
       if(input$Fruta_p == "Zarzamora"){ 
        fruta  <- data.frame(Fecha = as.Date(index(zar_usda()$Close)), Close = zar_usda()$Close)%>%
          filter(Fecha >= as.Date("2013-09-01"))%>%
          tiempos("Temporada")
             
        
        
       
        
       }else{
         if(input$Fruta_p == "Arandano"){
        fruta <- data.frame(Fecha = as.Date(index(ara_usda()$Close)), Close = ara_usda()$Close)%>%
          filter(Fecha >= as.Date("2013-09-01"))%>%
          tiempos("Temporada")
          
                 }
         
       }
    
   hc <- highchart(type  = "chart")%>%
   hc_xAxis(categories = sort(unique(data.frame(Semana = factor(c(1:52), 
                                                               levels = (c(34:85)%%52 + 1), 
                                                               ordered = TRUE))[,1])),
           crosshair = TRUE)%>%
    hc_chart(zoomType = "xy", panKey = "ctrl", panning = TRUE, backgroundColor = fondoplot)%>%
    hc_tooltip(crosshair = TRUE,
               shared = TRUE,
               split = FALSE)%>%
   hc_plotOptions(line = list(tooltip = list( useHTML= TRUE,
                                              headerFormat =  '<small>Semana:{point.key}</small><table>',
                                              pointFormat = '<br><tr><td style="color: {point.color}"> {series.name} : </td></br>
                                                             <br style="color: #000000"> {point.y} Cajas</br>' ,
                                              valueDecimals = 2)))
 if(input$Cat_usda == "Precio"){     
    
   for(var in sort(unique(fruta$Temporada))){
       
       x <- fruta%>%
         filter(Temporada == var)%>%
         tiempos("Semana")%>%
         ddply(.(Semana), 
               summarize,
               Promedio = mean(Close, na.rm = TRUE))%>%
         semanas(Campos = list(Promedio = NA))%>%
         arrange(Semana)
     
     serie <- list(list(x = x$Semana, data = x$Promedio, name = var))
     
      hc <- hc_add_series_list(hc, serie) 
       
     }}else{
       
      for(var in sort(unique(fruta$Temporada))){ 
       
       
       x <- fruta%>%
         filter(Temporada == var)%>%
         tiempos("Semana")%>%
         #ddply(.(Semana), 
          #     summarize,
           #    Promedio = mean(Close, na.rm = TRUE))%>%
         mutate(Promedio = Close)%>%
         semanas(Campos = list(Promedio = NA))%>%
         arrange(Fecha)
     
     serie <- list(list(x = x$Semana, data = x$Promedio, name = var))
     
      hc <- hc_add_series_list(hc, serie) 
     }
     
       
     
   }
   
   hc
  
    
   #Proyeccion
   
      }else{
          if(input$Tipo_p == "Proyeccion"){
            if(input$Fruta_p == "Zarzamora"){
              if(input$Cat_usda == "Precio"){
                
                fit <- read_rds("zar_fit.RDS")

    fruta <-  data.frame(Fecha = index(zar_usda()$Close), Close = zar_usda()$Close)%>%
      tiempos("Semanats")%>%
      ddply(.(Semanats), summarize, Promedio = mean(Close), Fecha = min(Fecha))%>%
      arrange(Semanats)
    
    
    fruta_ts <- ts(fruta$Promedio, 
                   start = c(min(as.integer(format(fruta$Fecha, 
                                                   format = "%Y"))), 
                             min(fruta$Semanats)),
                   frequency = 52)
              }else{
                fit <- read_rds("zar_fit.RDS")

    fruta <-  data.frame(Fecha = index(zar_usda()$Close), 
                         Promedio = zar_usda()$Close)%>%
      rename(Promedio = Close)%>%
      tiempos("Semanats")%>%
     # ddply(.(Semanats), summarize, Promedio = Close, Fecha = min(Fecha))%>%
      arrange(Semanats)
    
    
    fruta_ts <- ts(fruta$Promedio, 
                   start = c(min(as.integer(format(fruta$Fecha, 
                                                   format = "%Y"))), 
                             min(fruta$Semanats)),
                   frequency = 52)
              }
              
              
  
            
    
    
    }else{
              if(input$Fruta_p == "Arandano"){
                
                if(input$Cat_usda == "Precio"){
                        fit <- read_rds("ara_fit.RDS")
                
fruta <-  data.frame(Fecha = index(ara_usda()$Close), Close = ara_usda()$Close)%>%
      tiempos("Semanats")%>%
      ddply(.(Semanats), summarize, Promedio = mean(Close), Fecha = min(Fecha))%>%
      arrange(Semanats)
    
    fruta_ts <- ts(fruta$Promedio, 
                   start = c(min(as.integer(format(fruta$Fecha, 
                                                   format = "%Y"))), 
                             min(fruta$Semanats)),
                   frequency = 52)
                  
                }else{
                        fit <- read_rds("ara_fit.RDS")
                
fruta <-  data.frame(Fecha = index(ara_usda()$Close), 
                     Promedio = ara_usda()$Close)%>%
  rename(Promedio = Close)%>%
      tiempos("Semanats")%>%
    #  ddply(.(Semanats), summarize, Promedio = sum(Close), Fecha = min(Fecha))%>%
      arrange(Semanats)
    
    fruta_ts <- ts(fruta$Promedio, 
                   start = c(min(as.integer(format(fruta$Fecha, 
                                                   format = "%Y"))), 
                             min(fruta$Semanats)),
                   frequency = 52)
                }
              }
            }
        


x <- forecast(fit,h=5)


proyeccion <- data.frame(Semanats = max(fruta$Semanats)+ c(1:5),
                         Promedio = x$mean, 
                         Fecha = max(fruta$Fecha) +c(1:5)*7)%>%
  mutate(dt = datetime_to_timestamp(Fecha))
                         
range_80 <- data.frame(low = x$lower[,1], high = x$upper[,1], Fecha = proyeccion$dt)
range_95 <- data.frame(low = x$lower[,2], high = x$upper[,2], Fecha = proyeccion$dt)

df <- tail(fruta,8)%>%
  mutate(dt = datetime_to_timestamp(Fecha))

hc <- highchart()%>%
  hc_xAxis(type = "datetime", dateTimeLabelFormats = list(day = '%d of %b'))%>%
  hc_colors(colors = c('#6CF', '#39F', '#06C', '#036', '#000'))%>%
  hc_add_series(df, type = "line", hcaes(dt, Promedio), name = "Observado")%>%
  hc_add_series(proyeccion, type = "line", hcaes(dt, Promedio), name = "ets", zIndex = 3)%>%
    hc_add_series(range_95,  hcaes(x = Fecha), type = "arearange", name = "ets95%", color = "rgba(17,73, 132, .75)")%>%
    hc_add_series(range_80,  hcaes(x = Fecha), type = "arearange", name = "ets80%", color = "rgba(63,141, 216, .75)")%>%
      hc_plotOptions(line = list(tooltip = list( useHTML= TRUE,
                                             shared = TRUE,
                                             headerFormat =  '<small>Fecha: {point.key}</small><br>',
                                             pointFormat = '<br><br><tr><td style="color: #000000; font-size: 15px">
                                                            {series.name} : </td>
                                             <td style="color: #000000"> {point.y} USD <br></td></br><br><br>' ,
                                             valueDecimals = 2)),
                     arearange = list(tooltip = list(valueDecimals = 2)))%>%
                 
  hc_tooltip(crosshair = TRUE,
             shared = TRUE,
             split = FALSE)
  
  hc
            }
        }
    
  
    
})
```

Grafico 
----------------------------------------------------------------------------
###
```{r, context = "render"}

highchartOutput("Precios_master")

```


ENTRADAS {data-orientation=columns}
========================================================================

REGISTRO NUEVO
-----------------------------------------------

### {data-height=250}
```{r }
useShinyjs()
uiOutput("Prod_ent")

```


### {data-height=400}

```{r}
uiOutput("Ent_prod")
```


```{r context = "server"}

valores <- reactiveValues()


valores$Nombre_productos <- left_join(
  left_join(dbenv$productos%>%
              #filter(Activo == "A")%>%
              select(Clave_producto, Clave_presentacion, Clave_fruta, Nombre),
            dbenv$presentaciones%>%
              select(Clave_presentacion, Cantidad, Peso, Unidad)),
  dbenv$fruta%>%
    select(Clave_fruta, Nombre_corto, Variedad_corto, Tipo_corto))%>%
  collect()%>%
  transmute(Clave_producto = Clave_producto,
            Nombre_completo = paste0(Nombre, " ", Cantidad, "X", Peso, Unidad,
                                  " ", Nombre_corto, " ", Tipo_corto))
  
                            
                      

output$Prod_ent <- renderUI({
 
   
  
  tagList(
    useShinyjs(),
  disabled( 
  div(
    dateInput("Fecha_fruEmp", "Fecha:", value = Sys.Date()), style = "display: inline-block;vertical-align:bottom; width: 150px;"),
  
  div( selectizeInput("Productor", label = "Productor:", 
                 choices = paste(resumen_prod()$Clave_productor, resumen_prod()$Nombre_completo)), style = "display: inline-block;vertical-align:bottom; width: 300px; padding-left: 20px;"),
  
  div(textInput("Folio", "No_Folio:", value = ""), 
       style = "display: inline-block;vertical-align:top; width: 150px;"),

  tags$br(),
  
  
  
  div(selectizeInput("Cliente", "Cliente:", choices = c("ALFIN", "ALPASA"), 
                     selected = "ALFIN"),
      style = "display: inline-block;vertical-align:top; width: 200px; padding-left: 20px;")),
  
  div(actionButton("Nuevo_registro", "Nuevo Registro"),  
      style = "display: inline-block; width: 200px; padding-left: 20px;")
  )
})

output$Ent_prod <- renderUI({
  
  input$Palletizar
  
  tagList(
  
    div(selectizeInput("Producto", 
                       label = "Producto", 
                       choices = valores$Nombre_productos%>%
                        select(Nombre_completo) ),
        style = "display: inline-block;vertical-align:top; width: 300px; padding-right: 0px;"),
    
    div(numericInput("Precio", "Precio", value = 0),
      style = "display: inline-block;vertical-align:top; width: 100px;padding-left: 0px;"),
    
    div(textInput("Trazabilidad", "Trazabilidad", value = ""),
        style = "display: inline-block;vertical-align:top; width: 100px;"),
    
     div(selectizeInput("Calidad", "Calidad:", choices = c("A", "B", "C")),
        style = "display: inline-block;vertical-align:top; width: 100px;"),
    
    tags$br(),
    
    div(selectizeInput("Huerta", "Huerta:", choices = c(1,2), selected = 1),
        style = "display: inline-block;vertical-align:top; width: 200px;"),
    
    div(selectizeInput("Sector", "Sector:", choices = c(1:3), selected = 1),
        style = "display: inline-block;vertical-align:top; width: 133px;"),
    
     div(numericInput("Cantidad", "Cantidad", value = 0),
      style = "display: inline-block;vertical-align:top; width: 133px;"),

  div(numericInput("Rechazadas","Rechazadas", value = 0),
      style = "display: inline-block;vertical-align:top; width: 133px; "),
    
    
  
  tags$br(),
  
  div(textInput("Observaciones", "Observaciones:", value = ""),
       style = "display: inline-block;vertical-align:top;"),
  
  div(actionButton("Palletizar", "Palletizar"),
      style = "display: inline-block;vertical-align:center; justify-content: center; "),
  
  div(actionButton("Agregar_producto", "Agregar_producto"),
      style = "display: inline-block;vertical-align:center; justify-content: center; ")
  )
})
```


```{r context = "server"}

camposMother <- c("Fecha_fruEmp", "Productor", "Folio", "Cliente" )

camposChild <- c("Producto", "Precio", "Trazabilidad", "Calidad",  "Cantidad", "Rechazadas", "Observaciones")
observeEvent(input$Nuevo_registro, {
  walk(camposMother, enable)
})

```


###{data-height=350}
```{r context = "server"}


valores$fruEmp_reg <- data.frame()

observeEvent(input$Palletizar,{
  
  valores$fruEmp_reg <- bind_rows(valores$fruEmp_reg, jalarinputs(campos = camposChild, input = input))
  walk(camposMother, disable)

    
  })   



observeEvent(input$Guardar_fruta, {
  
  saveReg(mother = jalarinputs(camposMother, input = input)%>%
                 mutate(Clave_productor = str_match(Productor, "^[[0-9]]{0,3}")[,1],
                        Fecha_fruEmp = as.Date(as.numeric(Fecha_fruEmp), 
                                               origin = "1970-01-01"),
                        Folio = as.numeric(Folio))%>%
                 select(-Cliente, -Productor),
          
          
          motherTable = "fruEmp",
          
          child = valores$fruEmp_reg%>%
    rename(Nombre_completo = Producto)%>%
    merge(valores$Nombre_productos)%>%
    select(-Nombre_completo, Clave_producto)%>%
                 mutate(Id_fruEmp = nuevoId),
    
    childTable = "fruEmp_reg"
          
          )
  
  
 walk(disable, c(camposMother, camposChild))
  
})

output$Productos_reg <- renderText({
  kable3(valores$fruEmp_reg%>%
    rename(Nombre_completo = Producto)%>%
    merge(valores$Nombre_productos)%>%
      select(Clave_producto, Nombre_completo, Trazabilidad, Cantidad, Rechazadas,Calidad)
  
)
})
```

```{r}
htmlOutput("Productos_reg")
```


Prueba
--------------------------------------------------

###Pallets


```{r }
dataTableOutput("Palletizado")
```

```{r context = "server"}

#valores$pallets <-   myfetch("pallets")

output$Palletizado <- renderDataTable(
  dbr$pallets_reg%>%
  ddply(.(No_pallet), summarize, Total = sum(Cantidad))%>%
  mutate(Limite = 240,
         Faltantes = Limite-Total)%>%
  datatable())
  

```


###Palletizado

```{r}
actionButton("Guardar_fruta", "Grabar")
```
