---
title: "TANGANCICUARO"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    logo: images/logo.JPG
    favicon: images/logo.JPG
runtime: shiny_prerendered

---

```{r setup, include=FALSE}
options(shiny.port = 9999)
library(flexdashboard)
library(DT)
source("funciones.R")
library(shinyjs)

```

Column {data-width=650}
-----------------------------------------------------------------------

```{r context = "server-start"}
options(shiny.port = 9999)
library(RPostgres)
myfetch <- function(nombre,base = FALSE){
 
   tbl(con, nombre) 
 
 
}

con <- DBI::dbConnect(drv=RPostgres::Postgres(),
                      host = "localhost", 
                      dbname = "tangancicuaro", 
                      user = "postgres", 
                      password = "Cyan98150896", 
                      port = 5432)

library(tidyr)
library(kableExtra)
library(rhandsontable)
library(DBI)

```



```{r context = "server"}


   shinyInput <- function(FUN, len, id, ...) {
      inputs <- character(length(len))
      for (i in 1:length(len)) {
        clave <- len[i]
        inputs[i] <- as.character(FUN(paste0(id, clave), ...))
      }
      inputs
    }
#Productores

productores <- reactive({
  
  input$select_button
  
  input$Guardar_datos
  
  input$Guardar_alta
  
  input$Guardar_contactos
  
  myfetch("productores")%>%
  collect()
  })

telefonos <- reactive({ 
  
  input$Guardar_contactos
  
  myfetch("productoresContactos")%>%
  collect()})

resumen_prod <- reactive({
  
  
  
  productores()%>%
  mutate(Nombre_completo = paste(Nombre, Apellido_paterno, Apellido_materno))%>%
  select(Clave_productor, Nombre_completo)})


  data <- reactive({
    data.frame(
    Clave_productor = resumen_prod()$Clave_productor,  
    Nombre_completo = resumen_prod()$Nombre_completo,
    Delete = shinyInput(actionButton, 
                          resumen_prod()$Clave_productor, 
                          'button_', 
                          label = "Delete", 
                          onclick = 'Shiny.onInputChange(\"select_button\",  this.id)'),
      stringsAsFactors = FALSE,
      row.names = 1:length(resumen_prod()$Clave_productor))
  }) 

output$Resumen_prod <- renderDataTable(
  data()%>%
    arrange(Clave_productor),  server = FALSE, escape = FALSE, selection = 'none')

 
#reactivos


  Clave <- reactive({as.numeric(strsplit(input$select_button, "_")[[1]][2])})
  
  Name <- reactive({
    
    
    
    resumen_prod()%>%
      filter(Clave_productor == Clave())%>%
      mutate(Clave_nombre = paste(Clave_productor, Nombre_completo))%>%
      select(Clave_nombre)}) 
  #Datos
  datos <- reactive({
    productores()%>%
    filter(Clave_productor == Clave())%>%
    gather("Campo", "Valor")}) 
  #COntactos
  contactos <- reactive({
    input$Guardar_alta
     
    telefonos()%>%
    filter(Clave_productor == Clave())%>%
    select(Tipo, Contacto)
  })

#mostrar datos  
  
  observeEvent(input$select_button, {
  
      
  showModal(
      
    modalDialog(title = Name(),
      tabsetPanel(
          tabPanel("Contactos",  HTML(kable2(contactos()))),
          tabPanel("Datos",  HTML(kable2(datos())))
        ),
      footer = tagList(
          actionButton("Editar_datos", "Editar"),
          modalButton("CERRAR", 
                    icon = icon("window-close", 
                                class = NULL, 
                                lib = "font-awesome"))
        )))
  })
  
  
  
  observeEvent(input$Editar_datos,{
    
    showModal(
       modalDialog(title = Name(),
      tabsetPanel(
          tabPanel("Contactos", 
                   HTML(kable2(contactos())),
                   actionButton("Agregar_contacto", "NUEVO")),
          tabPanel("Datos",  rHandsontableOutput("Datos"))
        ),
      footer = tagList(
          actionButton("Guardar_datos", "Guardar", 
                       icon = icon("window-close", 
                                class = NULL, 
                                lib = "font-awesome")),
          modalButton("Cancelar", 
                    icon = icon("window-close", 
                                class = NULL, 
                                lib = "font-awesome")))
      
    
 
        ))
  
  })
    
#Datos editados
  
  output$Datos <- renderRHandsontable(rhandsontable(datos())%>%
                     hot_col("Campo", readOnly = TRUE))
  
  trigger_datos <- reactive({
    if(is.null(input$Datos)){return(datos())}
    else if(!identical(datos(),input$Datos)){
      # hot.to.df function will convert your updated table into the dataframe
      as.data.frame(hot_to_r(input$Datos))
    }
  })
  
  observeEvent(input$Guardar_datos,{
    
      input$Datos%>%
        hot_to_r()%>%
      spread("Campo", "Valor")%>%
        dbwriterow("Clave_productor", "Productores", Clave(), conn = con)
      
    
      removeModal()
  })

#output$Prueba <- renderDataTable(datatable((prueba()))) 

#Formulario Agregar contactos  
observeEvent(input$Agregar_contacto,
             {
               showModal(
                 modalDialog(title = Name(),
                             div(style="display: inline-block;vertical-align:top; width: 150px;",
                                 selectizeInput("Tipo_contacto", "TIPO", choices = c("Casa", "Celular", "Correo"))),
                             div(style="display: inline-block;vertical-align:top; width: 150px;",
                                 textInput(inputId = "Telefono_nuevo", label = "Contacto", placeholder = "Agregue  un  contacto")),
                             footer = tagList(
                               actionButton("Guardar_contactos", "Guardar", 
                                            icon = icon("window-close", 
                                                        class = NULL, 
                                                        lib = "font-awesome")),
                               modalButton("Cancelar", 
                                           icon = icon("window-close", 
                                                       class = NULL, 
                                                       lib = "font-awesome")))
                             
                            )
               )
               
             })


observeEvent(input$Guardar_contactos,
             {
            contactos <-   data.frame(Clave_productor = Clave() ,
                          Tipo = input$Tipo_contacto,
                          Contacto = input$Telefono_nuevo)
               
               dbWriteTable(con , name = "productoresContactos", contactos, append = TRUE)
               
               
               removeModal()
             })



#Modal Agregar Productor




#Formulario Alta


output$Test_clave_productor <- renderUI({
  if(input$Nueva_clave %in% productores()$Clave_productor){
 paste("Esta Clave ya esta siendo usada")
}
  })

labelMandatory <- function(label) {
  tagList(
    label,
    span("*", class = "mandatory_star")
  )
}

appCSS <- ".mandatory_star { color: red; }"



#Alta productores  
observeEvent(input$Alta_productor,
             {
               showModal(
                 modalDialog(
                  title = "Escriba los datos del productor",
                  tabsetPanel(
                    tabPanel(labelMandatory("Nombre"),
                             numericInput("Nueva_clave", label = "Clave Productor", value = max(c(max(productores()$Clave_productor),999)) + 1),
                             textInput("Nombre_productor", label = labelMandatory("Nombre") ),
                             textInput("Apellido_paterno", label = labelMandatory("Apellido Paterno")),
                             textInput("Apellido_materno", label = labelMandatory("Apellido Materno")),
                             uiOutput("Test_clave_productor"),
                             shinyjs::useShinyjs(),
                             shinyjs::inlineCSS(appCSS)
                    #actionButton("Agregar_huerta","Agregar Huerta")
                ),
                tabPanel("Datos", uiOutput("Direccion_alta")),
                tabPanel("Contactos", uiOutput("Contactos_alta")),
                tabPanel("Facturacion", uiOutput("Facturacion_alta")),
                tabPanel("Bancarios", uiOutput("Bancarios_alta")),
                tabPanel(labelMandatory("Huerta"), uiOutput("Huertas_alta"))),
                 # tags$head(tags$style(".modal-body{ min-height:700px}")),
                  size = "l",
                  footer =  tagList(
                    div(
                      style="display: inline-block;vertical-align:top; width: 150px;",
                      uiOutput("Guardar_alta")),
                    div(
                      style="display: inline-block;vertical-align:top; width: 150px;",
                      actionButton("Cerrar_alta", "CERRAR", 
                                # onclick = Shiny.onInputChange("output.Datos_alta", prueba),
                                 icon = icon("window-close", 
                                            class = NULL, 
                                            lib = "font-awesome"))))
                 )
               )
               
             }
             )

productor_alta <- reactive({
  data.frame(
    Clave_productor = input$Nueva_clave,
    Nombre = input$Nombre_productor,
    Apellido_paterno = input$Apellido_paterno,
    Apellido_materno = input$Apellido_materno,
    Direccion = ifelse(is.null(input$Direccion_productorAlta), "", input$Direccion_productorAlta),
    Localidad = ifelse(is.null(input$Localidad_productorAlta), "", input$Localidad_productorAlta),
    Municipio = ifelse(is.null(input$Municipio_productorAlta), "", input$Municipio_productorAlta),
    Estado = ifelse(is.null(input$Estado_productorAlta), "", input$Estado_productorAlta),
    RFC = ifelse(is.null(input$Rfc), "", input$Rfc),
    Nombre_facturacion = ifelse(is.null(input$Nombre_facturacion), "", input$Nombre_facturacion),
    Nombre_contador = ifelse(is.null(input$Nombre_contador), "", input$Nombre_contador),
    Correo_contador = ifelse(is.null(input$Correo_contador), "", input$Correo_contador),
    Telefono_contador = ifelse(is.null(input$Telefono_contador), "", input$Telefono_contador)
    
  )
}) 

#Formularios Alta

output$Direccion_alta <- renderUI({
  tagList(
  div(textInput("Direccion_productorAlta", "Direccion", value = "")),
  div(textInput("Localidad_productorAlta", "Localidad", value = "")),
  div(textInput("Municipio_productorAlta", "Municipio", value =  "TANGANCICUARO")),  
  div(textInput("Estado_productorAlta", "Estado", value  = "MICHOACAN"))
  )
  })
  
observeEvent(input$Telefono_alta, {
  cat(input$Direccion_productorAlta)
})

output$Contactos_alta <- renderUI ({
  tagList(
  div(textInput("Telefono_alta", "Telefono", value = "")),
  div(textInput("Celular_alta", "Celular", value = "")),
  div(textInput("Correo_alta", "E-mail", value = "")))
  
})

contactos_alta <- reactive({
  data.frame(Telefono_alta = ifelse(is.null(input$Telefono_alta),"", input$Telefono_alta),
             Celular_alta = ifelse(is.null(input$Celular_alta), "", input$Celular_alta),
             Correo_alta = ifelse(is.null(input$Correo_alta), "", input$Correo_alta)
  )%>%
    gather("Tipo","Contacto")%>%
    filter(Contacto != "")%>%
    mutate(Tipo = ifelse(Tipo == "Telefono_alta", "Casa",
                         ifelse(Tipo == "Celular_alta", "Celular",
                                ifelse(Tipo == "Correo_alta", "E-mail", ""))),
           Clave_productor = input$Nueva_clave)
})




output$Facturacion_alta <- renderUI({
  tagList(
    div(textInput("Nombre_facturacion", "Nombre o Razon Social", value = "")),
    div(textInput("Rfc", "RFC", value = "")),
    div(textInput("Nombre_contador", "Nombre del Contador", value = "")),
    div(textInput("Correo_contador", "E-mail del Contador", value = "")),
    div(textInput("Telefono_contador", "Telefono del contador", value = ""))
    
    
  )
})

output$Bancarios_alta <- renderUI({
  tagList(
    div(textInput("Titular", "Titular de la cuenta", value = "")),
    div(textInput("Banco", "Banco", value = "")),
    div(textInput("Cuenta", "Cuenta", value = "")),
    div(textInput("CLABE", "CLABE", value = ""))
    
  )
})


#Formulario huertas



output$Huertas_alta <- renderUI({
  tagList(
    div(textInput("Nombre_huerta", labelMandatory("Nombre de la Huerta")), style="display: inline-block;vertical-align:top; width: 300px;"),
    div(textInput("Alias_huerta", "Alias"), style="display: inline-block;vertical-align:top; width: 300px;"),
    tags$br(),
    div(numericInput("Superficie_huerta", labelMandatory("Superficie de la Huerta"), value = 0), style="display: inline-block;vertical-align:top; width: 300px;"),
    div(numericInput(inputId = "No_sectores",
                                       label = labelMandatory("Numero de Sectores"), 
                                       value = 1, min = 1
                                        ),style="display: inline-block;vertical-align:top; width: 300px;"),
    tags$br(),
    div(selectizeInput("Fruta_huerta", 
                       label = labelMandatory("Fruta"), 
                       choices = c("ZARZAMORA"), 
                       options = list(placeholder = "ZARZAMORA")), style="display: inline-block;vertical-align:top; width: 300px;"),
    div(textInput("Direccion_huerta", labelMandatory("Ubicacion")), style="display: inline-block;vertical-align:top; width: 300px;"),
    tags$br(),
    div(textInput("Localidad_huerta", labelMandatory("Localidad")), style="display: inline-block;vertical-align:top; width: 300px;"),
    div(textInput("Municipio_huerta", "Municipio", value = "TANGANCICUARO"), style="display: inline-block;vertical-align:top; width: 300px;"),
    div(textInput("Estado_huerta", "Estado", value = "MICHOACAN"), style="display: inline-block;vertical-align:top; width: 300px;"),
    tags$br(),
    div(rHandsontableOutput("Sectores_alta"))
  )
  
})



labelMandatory <- function(label) {
  tagList(
    label,
    span("*", class = "mandatory_star")
  )
}
  #Formulario Sectores

output$Sectores_alta <- renderRHandsontable(
  rhandsontable(
    data.frame(
      Clave_sector = 1:input$No_sectores,
      Superficie = input$Superficie_huerta/input$No_sectores
    )%>%
      mutate(Nombre = paste("SECTOR ", Clave_sector))
  )
)



#mandatorios Alta Productor
mandatoryAlta <- c("Nueva_clave", "Nombre_productor", "Apellido_paterno", "Apellido_materno")


 mandatoryFilled <- reactive({
  # check if all mandatory fields have a value
  mandatoryFilled <-
    vapply(mandatoryAlta,
           function(x) {
             !is.null(input[[x]]) && input[[x]] != ""
           },
           logical(1))
 
   all(mandatoryFilled)
  
  
  
})
 
 
 
 
output$Guardar_alta <- renderUI({
  if(mandatoryFilled()){
    actionButton(inputId = "Guardar_alta", "Guardar")
    }else(paste("Favor de llenar los campos con *"))
}) 
 

#Cerrar Alta
observeEvent(input$Cerrar_alta,{
 # output$Datos_alta
  removeModal()})

#Guardar Alta


cuentas_alta <- reactive({
  data.frame(
    Beneficiario = input$Titular,
    Banco = input$Banco,
    Cuenta = input$Cuenta,
    Clabe = input$CLABE 
  )%>%
    mutate(Clave_productor = input$Nueva_clave)
  
})



huertas_alta <- reactive({
  data.frame(
    Clave_huerta = 1,
    Clave_productor = input$Nueva_clave,
    Nombre = input$Nombre_huerta,
    Alias = input$Alias_huerta,
    Superficie = input$Superficie_huerta,
    Direccion = input$Direccion_huerta,
    Clave_fruta = 1,
    Localidad = input$Localidad_huerta,
    Municipio = input$Municipio_huerta,
    Estado = input$Estado_huerta,
    Zona = "",
    Activo = "A"
  )
})  


sectores_alta = reactive({
  input$Sectores_alta%>%
    hot_to_r()%>%
    mutate(Clave_productor = input$Nueva_clave,
           Clave_huerta = 1)
})

observeEvent(input$Guardar_alta,
             {
               
               dbBegin(con)
               tryCatch({
                   
              dbWriteTable(value = productor_alta(), name = "productores", conn = con, append = TRUE)
                 
              dbWriteTable(value =  contactos_alta(), name = "productoresContactos", conn = con , append = TRUE)
              
              dbWriteTable(value = cuentas_alta(), name = "productoresCuentas", conn = con, append = TRUE)
              
              dbWriteTable(value = huertas_alta(), name = "huertas", conn = con, append = TRUE)
              
              dbWriteTable(value = sectores_alta(), name = "sectores",conn = con, append = TRUE)
                 
               
                 },error = function(err){
                   print(paste("My errr", err))
                   dbRollback(con)
                 },#warning = function(w){
                   #  print(paste("My war:", w))
                   #},
            finally = {
              
              dbCommit(con)
              
              removeModal()
            })
             })



observeEvent(input$Agregar_huerta,
             {
               showModal(
                 modalDialog(
                   title = "HUERTA",
               tabsetPanel(
                 tabPanel("Huerta",
                          rHandsontableOutput("Huertas_alta")),
                 tabPanel("Sectores",
                          numericInput(inputId = "No_sectores",
                                       label = "Numero de Sectores", 
                                       value = 1
                                        ),
                          rHandsontableOutput("Sectores_alta")
                          )
               )
                 )
               )
             })




```


PRODUCTORES
===================================================




Prueba{.tabset}
------------------------------------------------------------

### Productores
```{r }


actionButton("Alta_productor", "Agregar Productor")

dataTableOutput("Resumen_prod")

```

###Prueba

```{r}
#dataTableOutput("Prueba")
```



